kind: pipeline
name: default
type: docker

steps:
  - name: build-and-deploy
    image: docker:17.12.0-ce
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    commands:
      - docker build -t next-app --build-arg ENV_VARIABLE=${ENV_VARIABLE} --build-arg NEXT_PUBLIC_ENV_VARIABLE=${NEXT_PUBLIC_ENV_VARIABLE} ./next-app
      - docker run -d -p 3000:3000 --restart=always --name=next-app next-app
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
